// Package netting is SetOff's multilateral netting algorithm.
//
// It is an independent implementation of setoff-engine (Rust). Both must
// produce identical results for every input; testdata/vectors holds the
// reference cases generated by the Rust engine.
package netting

import (
	"encoding/json"
	"fmt"
	"math/big"
	"sort"
	"strings"
)

// Amount is an integer in an asset's smallest unit, carried as a decimal
// string in JSON and bounded to the i128 range the contract uses.
type Amount struct{ big.Int }

var (
	maxI128 = new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 127), big.NewInt(1))
	minI128 = new(big.Int).Neg(new(big.Int).Lsh(big.NewInt(1), 127))
)

// NewAmount returns an Amount from an int64.
func NewAmount(v int64) Amount {
	var a Amount
	a.SetInt64(v)
	return a
}

// ParseAmount accepts canonical decimal integers only: no sign prefix, no
// leading zeros, no "-0".
func ParseAmount(s string) (Amount, error) {
	var a Amount
	digits := strings.TrimPrefix(s, "-")
	if digits == "" || strings.HasPrefix(s, "+") || (len(digits) > 1 && digits[0] == '0') || s == "-0" {
		return a, fmt.Errorf("not a canonical integer: %q", s)
	}
	for _, r := range digits {
		if r < '0' || r > '9' {
			return a, fmt.Errorf("not a canonical integer: %q", s)
		}
	}
	a.SetString(s, 10)
	if a.Cmp(maxI128) > 0 || a.Cmp(minI128) < 0 {
		return a, fmt.Errorf("amount %s exceeds the i128 range", s)
	}
	return a, nil
}

// MarshalJSON writes the amount as a string.
func (a Amount) MarshalJSON() ([]byte, error) { return json.Marshal(a.String()) }

// UnmarshalJSON reads a canonical decimal string.
func (a *Amount) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	v, err := ParseAmount(s)
	if err != nil {
		return err
	}
	*a = v
	return nil
}

// Obligation is something one participant owes another.
type Obligation struct {
	ID       string `json:"id"`
	Debtor   string `json:"debtor"`
	Creditor string `json:"creditor"`
	Asset    string `json:"asset"`
	Amount   Amount `json:"amount"`
}

// Position is a participant's net result in one asset; positive receives.
type Position struct {
	Asset       string `json:"asset"`
	Participant string `json:"participant"`
	Net         Amount `json:"net"`
}

// Transfer is one movement of the settlement plan.
type Transfer struct {
	Asset  string `json:"asset"`
	From   string `json:"from"`
	To     string `json:"to"`
	Amount Amount `json:"amount"`
}

// AssetSummary holds per-asset totals.
type AssetSummary struct {
	Asset       string `json:"asset"`
	Obligations int    `json:"obligations"`
	Gross       Amount `json:"gross"`
	Settled     Amount `json:"settled"`
	Transfers   int    `json:"transfers"`
}

// SavingBPS is the share of gross volume that never moves, in basis points.
func (s AssetSummary) SavingBPS() int64 {
	if s.Gross.Sign() == 0 {
		return 0
	}
	saved := new(big.Int).Sub(&s.Gross.Int, &s.Settled.Int)
	saved.Mul(saved, big.NewInt(10_000)).Quo(saved, &s.Gross.Int)
	return saved.Int64()
}

// Result of netting a window.
type Result struct {
	Positions []Position     `json:"positions"`
	Transfers []Transfer     `json:"transfers"`
	Assets    []AssetSummary `json:"assets"`
}

// Net nets a window of obligations. The result depends only on the set of
// obligations, not their order.
func Net(obligations []Obligation) (*Result, error) {
	ids := map[string]bool{}
	book := map[string]map[string]*big.Int{}
	count := map[string]int{}
	gross := map[string]*big.Int{}

	for _, o := range obligations {
		for field, v := range map[string]string{"id": o.ID, "debtor": o.Debtor, "creditor": o.Creditor, "asset": o.Asset} {
			if v == "" {
				return nil, fmt.Errorf("obligation %q: %s is empty", o.ID, field)
			}
		}
		switch {
		case o.Amount.Sign() <= 0:
			return nil, fmt.Errorf("obligation %s: amount must be positive", o.ID)
		case o.Debtor == o.Creditor:
			return nil, fmt.Errorf("obligation %s: debtor and creditor are the same", o.ID)
		case ids[o.ID]:
			return nil, fmt.Errorf("obligation %s: duplicate id", o.ID)
		}
		ids[o.ID] = true
		if book[o.Asset] == nil {
			book[o.Asset], gross[o.Asset] = map[string]*big.Int{}, new(big.Int)
		}
		if err := addTo(book[o.Asset], o.Debtor, new(big.Int).Neg(&o.Amount.Int)); err != nil {
			return nil, err
		}
		if err := addTo(book[o.Asset], o.Creditor, &o.Amount.Int); err != nil {
			return nil, err
		}
		count[o.Asset]++
		if err := checked(gross[o.Asset].Add(gross[o.Asset], &o.Amount.Int)); err != nil {
			return nil, err
		}
	}

	res := &Result{Positions: []Position{}, Transfers: []Transfer{}, Assets: []AssetSummary{}}
	for _, asset := range sortedKeys(book) {
		type side struct {
			who string
			amt *big.Int
		}
		var debtors, creditors []side
		settled := new(big.Int)
		for _, p := range sortedKeys(book[asset]) {
			n := book[asset][p]
			if n.Sign() != 0 {
				res.Positions = append(res.Positions, Position{Asset: asset, Participant: p, Net: Amount{*new(big.Int).Set(n)}})
			}
			switch n.Sign() {
			case -1:
				owed := new(big.Int).Neg(n)
				debtors = append(debtors, side{p, owed})
				if err := checked(settled.Add(settled, owed)); err != nil {
					return nil, err
				}
			case 1:
				creditors = append(creditors, side{p, new(big.Int).Set(n)})
			}
		}
		first := len(res.Transfers)
		for i, j := 0, 0; i < len(debtors) && j < len(creditors); {
			amt := new(big.Int).Set(debtors[i].amt)
			if creditors[j].amt.Cmp(amt) < 0 {
				amt.Set(creditors[j].amt)
			}
			res.Transfers = append(res.Transfers, Transfer{Asset: asset, From: debtors[i].who, To: creditors[j].who, Amount: Amount{*amt}})
			debtors[i].amt.Sub(debtors[i].amt, amt)
			creditors[j].amt.Sub(creditors[j].amt, amt)
			if debtors[i].amt.Sign() == 0 {
				i++
			}
			if creditors[j].amt.Sign() == 0 {
				j++
			}
		}
		res.Assets = append(res.Assets, AssetSummary{
			Asset: asset, Obligations: count[asset], Gross: Amount{*gross[asset]}, Settled: Amount{*settled},
			Transfers: len(res.Transfers) - first,
		})
	}
	return res, nil
}

func addTo(m map[string]*big.Int, who string, delta *big.Int) error {
	if m[who] == nil {
		m[who] = new(big.Int)
	}
	return checked(m[who].Add(m[who], delta))
}

// checked mirrors the Rust engine's i128 overflow errors.
func checked(v *big.Int) error {
	if v.Cmp(maxI128) > 0 || v.Cmp(minI128) < 0 {
		return fmt.Errorf("amounts overflow")
	}
	return nil
}

// sortedKeys orders map keys by byte value, as Rust's BTreeMap does.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
